# Generated by Django 3.1 on 2021-01-08 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(default='', max_length=50)),
                ('subcategory', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=50)),
                ('image', models.ImageField(default='', upload_to='')),
                ('price', models.IntegerField(default=0)),
                ('offer_price', models.BooleanField()),
            ],
        ),
    ]
