# Generated by Django 3.1 on 2021-01-11 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_register'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='maniesh',
            new_name='user',
        ),
    ]
